export enum FilterType {
  CHECKBOX = "CHECKBOX",
  RADIO = "RADIO",
  INPUT = "INPUT",
  INPUT_NUMBER = "INPUT_NUMBER",
  DATE_RANGE_PICKER = "DATE_RANGE_PICKER",
  DATE_TIME_RANGE_PICKER = "DATE_TIME_RANGE_PICKER",
}
